name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/zap-linux-amd64 cmd/zap/main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/zap-darwin-amd64 cmd/zap/main.go
          GOOS=windows GOARCH=amd64 go build -o dist/zap-windows-amd64.exe cmd/zap/main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/zap-linux-amd64
            dist/zap-darwin-amd64
            dist/zap-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
